# Site settings
title: Rendszermodellez√©s jegyzet
baseurl: "/remo-jegyzet/" # the subpath of your site, e.g. /blog/
url: "http://docs.inf.mit.bme.hu/" # the base hostname & protocol for your site

markdown: kramdown

repo: https://github.com/FTSRG/remo-jegyzet
